apiVersion: v2
name: java-task
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: redis
  version: "15.5.5"
  condition: redis.enabled
  repository: "https://charts.bitnami.com/bitnami"
- name: memcached
  version: "5.15.8"
  condition: memcached.enabled
  repository: "https://charts.bitnami.com/bitnami"
- name: kafka
  version: "14.4.0"
  condition: kafka.enabled
  repository: "https://charts.bitnami.com/bitnami"
- name: postgresql
  version: "10.13.8"
  condition: postgresql.enabled
  repository: "https://charts.bitnami.com/bitnami" 
