{{- range .Values.classes }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" $ }}-{{ .shortName }}
  labels:
    {{- include "labels" $ | nindent 4 }}-{{ .shortName }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}-{{ .shortName }}
{{- end }}
